openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/users/{userId}:
    put:
      tags:
      - user-controller
      operationId: updateUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/users/{userId}/{targetUserId}:
    put:
      tags:
      - user-controller
      operationId: updateUserRole
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: targetUserId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/users/{userId}/teams/{teamId}/{targetProjectId}:
    put:
      tags:
      - user-controller
      operationId: assignProjectToTeam
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: targetProjectId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TeamDTO'
  /api/users/{userId}/teams/{teamId}/assignUser/{targetUserId}:
    put:
      tags:
      - user-controller
      operationId: assignUserToTeam
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: targetUserId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/users/{userId}/tasks/{taskId}:
    get:
      tags:
      - user-controller
      operationId: getTaskById
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskDTO'
    put:
      tags:
      - user-controller
      operationId: completeTaskObjective
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskDTO'
  /api/users/{userId}/tasks/{taskId}/{targetUserId}:
    put:
      tags:
      - user-controller
      operationId: assignTask
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: targetUserId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/users/{userId}/tasks/{taskId}/review:
    put:
      tags:
      - user-controller
      operationId: reviewTask
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskDTO'
  /api/users:
    get:
      tags:
      - user-controller
      operationId: getUsers
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
    post:
      tags:
      - user-controller
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/users/{userId}/teams:
    post:
      tags:
      - user-controller
      operationId: createTeam
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TeamDTO'
  /api/users/{userId}/teams/{teamId}/{targetUserId}:
    post:
      tags:
      - user-controller
      operationId: assignTeamLeader
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: targetUserId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TeamDTO'
  /api/users/{userId}/tasks:
    get:
      tags:
      - user-controller
      operationId: getAllTasksForUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskDTO'
    post:
      tags:
      - user-controller
      operationId: createTask
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskDTO'
  /api/users/{userId}/tasks/{taskId}/comments:
    post:
      tags:
      - user-controller
      operationId: addCommentToTask
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskDTO'
  /api/users/{userId}/projects:
    post:
      tags:
      - user-controller
      operationId: createProject
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectDTO'
  /api/users/{userId}/tasks/filtered:
    get:
      tags:
      - user-controller
      operationId: getFilteredTasks
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: parameters
        in: query
        required: true
        schema:
          type: object
          additionalProperties:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskDTO'
  /api/users/{id}:
    get:
      tags:
      - user-controller
      operationId: getUserById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
  /api/teams:
    get:
      tags:
      - team-controller
      operationId: getAllTeams
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamDTO'
  /api/teams/{id}:
    get:
      tags:
      - team-controller
      operationId: getTeamById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TeamDTO'
  /api/tasks:
    get:
      tags:
      - task-controller
      operationId: getTasks
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskDTO'
  /api/tasks/{id}:
    get:
      tags:
      - task-controller
      operationId: getTaskById_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TaskDTO'
  /api/projects:
    get:
      tags:
      - project-controller
      operationId: getAllProjects
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDTO'
  /api/projects/{id}:
    get:
      tags:
      - project-controller
      operationId: getProjectById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectDTO'
    delete:
      tags:
      - project-controller
      operationId: deleteProject
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        percentageComplete:
          type: number
          format: double
        description:
          type: string
        team:
          $ref: '#/components/schemas/Team'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        done:
          type: boolean
        complete:
          type: boolean
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        createdBy:
          type: string
        status:
          type: string
          enum:
          - TO_DO
          - IN_PROGRESS
          - AWAITING_REVIEW
          - IN_REVIEW
          - DONE
        priority:
          type: string
          enum:
          - HIGH
          - MEDIUM
          - LOW
        progress:
          type: number
          format: double
        dueDate:
          type: string
          format: date
        completedBy:
          type: string
        reviewedBy:
          type: string
        user:
          $ref: '#/components/schemas/User'
        project:
          $ref: '#/components/schemas/Project'
        comments:
          type: object
          additionalProperties:
            type: string
        objectives:
          type: object
          additionalProperties:
            type: boolean
        objectiveMapComplete:
          type: boolean
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        teamLeaderId:
          type: integer
          format: int64
        project:
          $ref: '#/components/schemas/Project'
        userList:
          type: array
          items:
            $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
          enum:
          - JUNIOR
          - MEDIOR
          - SENIOR
          - PROJECT_MANAGER
          - TEAM_LEADER
        email:
          type: string
        tasksForUser:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        team:
          $ref: '#/components/schemas/Team'
    UserDTO:
      required:
      - email
      - firstName
      - lastName
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          maxLength: 30
          minLength: 3
          type: string
        lastName:
          maxLength: 30
          minLength: 3
          type: string
        role:
          type: string
          enum:
          - JUNIOR
          - MEDIOR
          - SENIOR
          - PROJECT_MANAGER
          - TEAM_LEADER
        email:
          type: string
        tasksForUser:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        team:
          $ref: '#/components/schemas/Team'
    TeamDTO:
      required:
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 30
          minLength: 3
          type: string
        teamLeaderId:
          type: integer
          format: int64
        project:
          $ref: '#/components/schemas/Project'
        userList:
          type: array
          items:
            $ref: '#/components/schemas/User'
    TaskDTO:
      required:
      - description
      - objectives
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          maxLength: 30
          minLength: 3
          type: string
        description:
          maxLength: 100
          minLength: 3
          type: string
        createdBy:
          type: string
        status:
          type: string
          enum:
          - TO_DO
          - IN_PROGRESS
          - AWAITING_REVIEW
          - IN_REVIEW
          - DONE
        priority:
          type: string
          enum:
          - HIGH
          - MEDIUM
          - LOW
        progress:
          type: number
          format: double
        dueDate:
          type: string
          format: date
        completedBy:
          type: string
        reviewedBy:
          type: string
        comments:
          type: object
          additionalProperties:
            type: string
        objectives:
          type: object
          additionalProperties:
            type: boolean
        project:
          $ref: '#/components/schemas/Project'
        user:
          $ref: '#/components/schemas/User'
        objectiveMapComplete:
          type: boolean
    ProjectDTO:
      required:
      - description
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 30
          minLength: 3
          type: string
        percentageComplete:
          type: number
          format: double
        description:
          maxLength: 250
          minLength: 3
          type: string
        team:
          $ref: '#/components/schemas/Team'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        done:
          type: boolean
        complete:
          type: boolean
